### ISSUE TITLE
Docker doesn't have rsync

### ISSUE THREAD

**Issue by ashgillman** [SyneRBI/SIRF-Exercises#104]
When building Docker:

```
/devel/SIRF-Exercises/scripts/download_data.sh: line 195: rsync: command not found
```

**Comment by ashgillman** [comment]
I used `rsync` for the `-u` and `-a` flags, but on closer inspection, good old `cp` supports these

**Comment by KrisThielemans** [comment]
ok. what about checking if `rsync` is present, if so use it, otherwise use `cp`? More complicated, but `rsync` does feel nicer. It could prevent problems with files being open in one notebook, and people redownloading again by accident.

**Comment by ashgillman** [comment]
I think `cp -ua X Y` and `rsync -ua X Y` are almost functionally equivalent? Make a copy, but only if src is newer, and maintain all file metadata?

**Comment by KrisThielemans** [comment]
alright! I didn't know that.

Please check if MacOS `cp` supports it...

**Comment by ashgillman** [comment]
No, MacOS doesn't...
I'll make a function

**Comment by ashgillman** [comment]
It was getting bigger than Ben Hur, I think just using cp is acceptable. These scripts I suppose would be re-written in Python for #83 ?

**Comment by KrisThielemans** [comment]
agreed
