### ISSUE TITLE
MacOS doesn't have md5sum

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-Exercises#105]
Noticed by @DANAJK .

searching online finds lots of links that `md5` outputs the hash, but nothing that checks the md5. sigh

**Comment by KrisThielemans** [comment]
@DANAJK could you check if the following gives similar output to the stored md5
```sh
md5 -r PTB_ACRPhantom_GRAPPA.zip
```
If so, the following would be a replacement I believe, so could you check that as well?
```sh
md5 -r PTB_ACRPhantom_GRAPPA.zip | diff -q PTB_ACRPhantom_GRAPPA.zip.md5
# check in terminal
echo $?
```
the latter should print `0`. If it does, we want to check with a wrong file as well
```sh
md5 -r PTB_ACRPhantom_GRAPPA.zip.md5 | diff -q PTB_ACRPhantom_GRAPPA.zip.md5
# check in terminal
echo $?
```
should print `1`

**Comment by DANAJK** [comment]
In a Mac terminal, `md5 -r PTB_ACRPhantom_GRAPPA.zip` gives `a7e0b72a964b1e84d37f9609acd77ef2 PTB_ACRPhantom_GRAPPA.zip` which seems to correspond correctly to the file `PTB_ACRPhantom_GRAPPA.zip.md5`

However, I don't seem to be able to correctly pipe to `diff` (maybe the output from md5 is not a file?):
```
(base) davidatkinson@Davids-MacBook-Pro devel % md5 -r PTB_ACRPhantom_GRAPPA.zip | diff -q PTB_ACRPhantom_GRAPPA.zip.md5
diff: missing operand after `PTB_ACRPhantom_GRAPPA.zip.md5'
diff: Try `diff --help' for more information.
```
and I don't understand why not.

**Comment by KrisThielemans** [comment]
ok, what about
```
md5 -r PTB_ACRPhantom_GRAPPA.zip > test.md5
diff -q test.md5 PTB_ACRPhantom_GRAPPA.zip.md5
```

**Comment by DANAJK** [comment]
Yes, that works, along with the `echo $?`
