### ISSUE TITLE
MR notebooks

### ISSUE THREAD

**Issue by DANAJK** [SyneRBI/SIRF-Exercises#112]
I checked the MR notebooks labelled a-e (there is an 'f' mentioned in the Excel spreadsheet but I didn't have that).

I was using the latest `service` Docker, but I assume this is currently equivalent to `v3.1.0-rc.1-service` as it had the same date and time when I pulled it.

in `d_undersampled_reconstructions`:
1) `get_info` is deprecated and should be replaced by `parameter_info`
2) There is a bug in the Coil Sensitivity Map computation section: `ax = fig.add_subplot(2,num_channels//m2,c+1)` should be `ax = fig.add_subplot(2,num_channels//2,c+1)` (the m2 should be 2)

Otherwise, I was able to run them all.

**Comment by KrisThielemans** [comment]
> 1. `get_info` is deprecated and should be replaced by `parameter_info`

Actually, I think we should revert that deprecation. It was based on comments in https://github.com/SyneRBI/SIRF/issues/829, which probably weren't clear (sorry). In
https://github.com/SyneRBI/SIRF/issues/947#issuecomment-860917043 I suggested to replace the name with `get_kspace_info`. Please confirm if that's a sensible name.

**Comment by KrisThielemans** [comment]
> `get_kspace_info`. Please confirm if that's a sensible name.

probably not... Please comment in https://github.com/SyneRBI/SIRF/issues/947

**Comment by KrisThielemans** [comment]
now called `get_ISMRMRD_info` since merging of https://github.com/SyneRBI/SIRF/pull/962. A volunteer to correct the notebook?
