### ISSUE TITLE
Docker does not need to start gadgetron, but instructions say you do. 

### ISSUE THREAD

**Issue by AnderBiguri** [SyneRBI/SIRF-Exercises#113]
https://github.com/SyneRBI/SIRF-Exercises/blob/master/DocForParticipants.md

**Comment by KrisThielemans** [comment]
Right, I edited the `README` and forgot to push that, so did that just now. However, now there's a lot of overlap between that file and this one, which I hadn't spotted...

**Comment by AnderBiguri** [comment]
@KrisThielemans I think that the Readme should be the "Docs for participants" really. Makes it easier to maintain and its the first thing you see, so it is more natural to read that. So probably best to have all the info on those docs in the readme and remove the file itself.

**Comment by AnderBiguri** [comment]
Well just saw your email where you prefer to put everything in DocForParticipants. 

Happy to do that, but just to be clear: everything but the repo info, authors and summary goes to DocForParticipants? Most of the Readme are Docs for participants conceptually.

**Comment by KrisThielemans** [comment]
yeah, I think that makes most sense. README should be short and point to other places (i.e. install, docfor participants, probably also docforinstructors).

**Comment by KrisThielemans** [comment]
In the end, it doesn't matter too much where we put it, as long as it is in one place only!

**Comment by AnderBiguri** [comment]
Are there instructions for the cluster? Should I just go and replace all the Azure instructions, or remove them?

**Comment by KrisThielemans** [comment]
no instructions for the STFC cluster yet. @paskino I suggest we put them on HackMD.

Please leave Azure instructions in place. One day, we'll reenable that. just make sure that it clearly says "if your instructors tell you..."
