### ISSUE TITLE
Defragmenting docs: VM installation

### ISSUE THREAD

**Issue by AnderBiguri** [SyneRBI/SIRF-Exercises#122]
Currently, to point a newbie from this repo to installation instructions, we need to point them to

https://github.com/SyneRBI/SIRF/wiki/How-to-obtain-SIRF

Which for the VM points to 

http://www.ccpsynerbi.ac.uk/downloads

But we also need to point them to 

https://github.com/SyneRBI/SIRF-Exercises/blob/master/INSTALL.md

Which has more information on the VM, including direct links to 

https://github.com/SyneRBI/SyneRBI_VM/blob/master/INSTALL.md

All in all a bit fragmented. My suggestion would be to remove this second path. The INSTALL.md at SIRF-Exercises can be removed by adding this information to the SIRF repo, where its partially there.  

This is not a current priority, lets leave it for after the training course.

**Comment by KrisThielemans** [comment]
There certainly is repetition that needs to be culled. However, it sort of implies fragmentation. It's neater to have everything in one place but it is unmaintainable.

I'm hoping that the wiki or downloads page points to https://github.com/SyneRBI/SyneRBI_VM/blob/master/INSTALL.md. That file we cannot get rid of.

The SIRF-Exercises INSTALL has to talk about installing the SIRF-Exercises. Should be really brief on VM/Docker (i.e. you don't need to read this), but for self-build people it needs to contain the relevant info that's there.

too many options, I'm sure. It'll be hard to do this well, but hopefully not too hard to do it better 😄

**Comment by AnderBiguri** [comment]
I would suggest to completely remove anything that is not self-build in the SIRF-Exercises INSTALL, except a single line saying "this is for self build, otherwise go to -> https://github.com/SyneRBI/SIRF/wiki/How-to-obtain-SIRF"

**Comment by KrisThielemans** [comment]
sure

**Comment by AnderBiguri** [comment]
There are 2 sets of instructions for the VM (which I don't have installed now) on this page, one in README, anther one in the docs for participants. 

On the README: 

https://github.com/SyneRBI/SIRF-Exercises#starting-the-jupyter-server

Of the participants Docs:

https://github.com/SyneRBI/SIRF-Exercises/blob/master/DocForParticipants.md#using-the-vm

I am a bit confused here. The second one seems to assume jupyter can just run on the VM. Does this docs assume you have run first what is in the README, or are the README docs not needed?

I am trying to avoid downloading the VM by asking, but do let me know if this needs testing.

**Comment by KrisThielemans** [comment]
Probably the best thing to do is to move the information from the first item to https://github.com/SyneRBI/SyneRBI_VM/blob/master/documentation/Basic-usage.md.

**Comment by AnderBiguri** [comment]
If they are not needed to start the VM and jupyter, I agree.  

Still not sure if they are needed, I guess I'd need to try it....
