### ISSUE TITLE
Jupyterhub: Path to real data in NEMA IQ example

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-Exercises#123]
In the [PET reconstruct real data notebook](https://github.com/SyneRBI/SIRF-Exercises/blob/master/notebooks/PET/reconstruct_measured_data.ipynb) we rely on the user to run the script `convertSiemensInterfileToSTIR.sh` to convert the Siemens to a STIR readable interfile file header. Now, on the jupyterhub the cell that is supposed to run that does not work for multiple reasons.

I have therefore pre-run the script and the output is in the same directory of the data (in the read-only filesystem).

There’s a cell which I copied here that sets the paths of the various files. 

```python
#%% set filenames 
# input files
list_file = os.path.join(data_path, '20170809_NEMA_60min_UCL.l.hdr')
norm_file = 'norm.n.hdr'
attn_file = 'umap.v.hdr'
# output filename prefixes
sino_file = 'sino'
%ls
```

This cell is presupposing that the users have run the script themselves and the result is in the current working directory. This is not the case in jupyterhub. So what needs doing is either:

1. give the full path of `norm.n.hdr` and `umap.v.hdr` (which are in the same `data_path` as the `list_file`)
2. copy the files in the current working directory

In either case the notebook requires some modifications. Which is the preferred solution?

I vote for 1.

**Comment by KrisThielemans** [comment]
1 seems to be fine. It would need to work on the VM etc as well though. I'll be checking this notebook later today (I hope), but please fix it first.

**Comment by paskino** [comment]
I close this as almost duplicate of #120 
Let's continue the conversation there
