### ISSUE TITLE
HKEM notebook refers to data that doesn't exist

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-Exercises#124]
The notebook makes use of some data that is not available and it is not explained how to get it. Possibly it should be executed after the [BrainWeb](https://github.com/SyneRBI/SIRF-Exercises/blob/master/notebooks/Synergistic/BrainWeb.ipynb) notebook, though I tried it and that's not sufficient.

```python
brainweb_sim_data_path = exercises_data_path('working_folder', 'Synergistic', 'BrainWeb')

# few lines below
sino = pet.AcquisitionData(os.path.join(brainweb_sim_data_path, 'FDG_tumour_sino_noisy.hs'))
```
```
File: /opt/SIRF-SuperBuild/INSTALL/python/sirf/STIR.py
Line: 788
check_status found the following message sent from the engine:
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-4-c788f07929de> in <module>
----> 1 sino = pet.AcquisitionData(os.path.join(brainweb_sim_data_path, 'FDG_tumour_sino_noisy.hs'))
      2 
      3 #%% the following multiplication is just in case the noise sinogram has a different scale from the noiseless
      4 # you can remove it in a real data situation
      5 sino = sino*1000

/opt/SIRF-SuperBuild/INSTALL/python/sirf/STIR.py in __init__(self, src, span, max_ring_diff, view_mash_factor)
    786         else:
    787             raise error('Wrong source in AcquisitionData constructor')
--> 788         check_status(self.handle)
    789 
    790     def __del__(self):

/opt/SIRF-SuperBuild/INSTALL/python/sirf/Utilities.py in check_status(handle, stack)
    421             repr(line) + ' of ' + file + '; ' + \
    422             'the reconstruction engine output may provide more information'
--> 423         raise error(errorMsg)
    424 
    425 

error: ??? "'ProjData::read_from_file: error opening file /mnt/materials/SIRF/Fully3D/SIRF/working_folder/Synergistic/BrainWeb/FDG_tumour_sino_noisy.hs' exception caught at line 320 of /opt/SIRF-SuperBuild/sources/SIRF/src/xSTIR/cSTIR/cstir.cpp; the reconstruction engine output may provide more information"
```

**Comment by ashgillman** [comment]
I will check if this tonight. Also tagging @danieldeidda

**Comment by ashgillman** [comment]
The file definitely doesn't exist? Not some other error?

And yes, you were right, in order to run this notebook you need to first run the Brainweb notebook (not the single slice one).

**Comment by ashgillman** [comment]
What is the best way to test this with as close an environment to the training school? Docker obviously, but any specific tag?

**Comment by KrisThielemans** [comment]
`service`. It's a few SIRF commits old, but as Travis ran out of credits again, and they haven't replied in a week, I cannot push another one. (I guess we could push by hand...). in any case, that shouldn't matter for this one.

**Comment by ashgillman** [comment]
I've just run this notebook on Docker and seemed to work fine. Note that you have to run the BrainWeb.ipynb notebook to completion, it is the very last cell that creates the required image.

**Comment by KrisThielemans** [comment]
other things wrong in this notebook. Fixing it today.
