### ISSUE TITLE
SIRF-Exercises cannot be run unless download_data.sh is called!!!

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-Exercises#134]
This is because `cd_to_working_dir` fails.

**Comment by KrisThielemans** [comment]
Yes, but you're behind the curve. #127 should make sure you can run it without downloading anything.
not ideal but this is where we are at the moment. I think Intro notebooks tell you clear enough what to do.

**Comment by ashgillman** [comment]
#126
