### ISSUE TITLE
Does reconstruct_measured_data run on JupyterHub with the cp command

### ISSUE THREAD

**Issue by ashgillman** [SyneRBI/SIRF-Exercises#141]
interesting, is it going to fail on JupyterHub (and docker) due to read-only location? Better to write it in the current dir?

_Originally posted by @KrisThielemans in https://github.com/SyneRBI/SIRF-Exercises/pull/140#discussion_r659504052_

**Comment by ashgillman** [comment]
Related #120 - I was under the impression this was somehow fixed?

@paskino

**Comment by KrisThielemans** [comment]
resolved, albeit it in a somewhat ugly way
