### ISSUE TITLE
problem in PET/reconstruct_measured_data due to SIRF bug

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-Exercises#146]
Due to https://github.com/SyneRBI/SIRF/issues/983, randoms and scatter background terms are currently ignored in this notebook...

Current work-around is to replace
```
acq_model.set_background_term(randoms+scatter_estimate)
```
with
```
acq_model.set_additive_term(asm.invert(randoms+scatter_estimate))
```

Note: the "additive" term is precorrected for the acquisition sensitivity, while the "background" term is not. See `help(AcquisitionModel)`

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov can you please check this one? should be fixed now

**Comment by evgueni-ovtchinnikov** [comment]
seems to work fine
