### ISSUE TITLE
path problem in synergistic notebooks

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-Exercises#148]
See https://hackmd.io/@SIRF-CIL-Fully3D/SkZqjSf3O#Q-Data-not-downloaded-on-cloud

**Comment by samdporter** [comment]
These path issues can be fixed in the VM with a little bit of tweaking (though I'm getting a jupyter server error so can't test it atm), but I think anything we do will cause problems in the STFC cloud. Currently the data is downloaded to "/mnt/materials/SIRF/Fully3D/SIRF/" which is Read-only.

**Comment by DANAJK** [comment]
> These path issues can be fixed in the VM with a little bit of tweaking (though I'm getting a jupyter server error so can't test it atm), but I think anything we do will cause problems in the STFC cloud. Currently the data is downloaded to "/mnt/materials/SIRF/Fully3D/SIRF/" which is Read-only.

Yes. This means we can’t get started because the cd_to_working_dir tries to create a directory, but cannot.

**Comment by DANAJK** [comment]
>Yes. This means we can’t get started because the cd_to_working_dir tries to create a directory, but cannot.

Works if you first run the bash script 'download_data.sh' (without the '-h') described in notebook  Introductory/introduction.ipynb

**Comment by KrisThielemans** [comment]
@samdporter I believe you fixed this in #173 (or earlier)?

**Comment by samdporter** [comment]
Yes. This works as long as the introduction nb (or just the bash script) is run
