### ISSUE TITLE
Singleton first dimension problems in BrainWeb-single_slice_motion.ipynb

### ISSUE THREAD

**Issue by DANAJK** [SyneRBI/SIRF-Exercises#154]
**BrainWeb-single_slice_motion.ipynb**

After `FDG_arr  = vol['PET']`, the shape of `FDG_arr` is (127,344,344).

Then after
   slice = FDG_arr.shape[0]//2
   FDG_arr  = FDG_arr[slice,:,:]

`FDG_arr` has shape (344,344) (i.e. there has been a secret squeeze). This subsequently causes problems with `im.fill(vol)` because `vol` is derived from `FDG_arr` and is thus 2D (despite the name `vol`), whereas `im` is 3D (despite the name) and has a singleton first dimension so you can't fill `im` with `vol`.

**Comment by paskino** [comment]
I guess we need to use numpy [`expand_dims`](https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html)

Something like this might work

```python 

vol = np.expand_dims(vol, axis=0)
```

**Comment by DANAJK** [comment]
Also the BrainWeb notebook

**Comment by NicoleJurjew** [comment]
I changed the BrainWeb-single_slice_motion.ipynb notebook. @DANAJK is right, the same function is implemented in the BrainWeb notebook. It deals with the entire 3D array rather than cropping to a 2D image, though, so the error doesn't occur for me.
