### ISSUE TITLE
matplotlib

### ISSUE THREAD

**Issue by DANAJK** [SyneRBI/SIRF-Exercises#177]
Seems like on STFC cloud, notebooks need to use `%matplotlib inline` instead of  `%matplotlib notebook`. I have added a note on the HackMD site.

**Comment by KrisThielemans** [comment]
please try `%matplotlib widget` as well? (we've switched to JupyterLab)

**Comment by DANAJK** [comment]
> please try `%matplotlib widget` as well? (we've switched to JupyterLab)

 `%matplotlib widget` gives an error

**Comment by KrisThielemans** [comment]
sigh. which one? Probably need `ipypml`? I though @paskino has added it.
could install via conda https://anaconda.org/conda-forge/ipympl or pip and see what happens...

**Comment by DANAJK** [comment]
Error is "Warning: Cannot change to a different GUI toolkit: widget. Using notebook instead."

**Comment by KrisThielemans** [comment]
there's also https://stackoverflow.com/questions/52703190/cannot-change-to-a-different-gui-toolkit-notebook-warning-in-jupyter which I don't understand

**Comment by KrisThielemans** [comment]
> could install via conda https://anaconda.org/conda-forge/ipympl or pip and see what happens

doesn't help

**Comment by KrisThielemans** [comment]
`%matplotlib widget` does work if done BEFORE ANYTHING ELSE.

**Comment by KrisThielemans** [comment]
hackMD updated. Ideally update the doc in the repo as well.
