### ISSUE TITLE
4_setup_training notebook deep learning

### ISSUE THREAD

**Issue by danieldeidda** [SyneRBI/SIRF-Exercises#184]
I am trying to run the deep learning notebooks but the last one fails at the 3rd cell. with the following error:

UnpicklingError: invalid load key, '<'.

it seems something is wrong with the downloaded data in the previous cell
@Imraj-Singh

**Comment by Imraj-Singh** [comment]
@danieldeidda, this is my bad, that link points to the trained model in my personal OneDrive account that is now non-existent. The code can still work without the trained model, and you could train you own. This was a problem in the lead up to PSMR as saving the model in this repository bloats it, and OneDrive was my quick fix. Zenodo was mentioned as a place to put data, but I am not sure if I should have my own personal Zenodo, or if there is a SyneRBI zendo that it could be added to? @KrisThielemans what is you opinion?

**Comment by DANAJK** [comment]
There is a SyneRBI community on Zenodo. I'll send you an upload link.

**Comment by Imraj-Singh** [comment]
Great, thanks! I'll retrain and upload soon.

**Comment by Imraj-Singh** [comment]
#185 created a pull request with a fix
