### ISSUE TITLE
SPECT Y90 data

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-Exercises#188]
The SPECT notebook(s) contain
```
!pwd
!cp -r /mnt/materials/SIRF/PSMRTBP2022/Y90-NEMA-NPL/SPECT/* .
!ls .
```
and commented-out lines to download the data.

ideally this data-set is on Zenodo, and we add it to the `download_data.sh` script. In addition, the above lines rely on Linux and should  be replaced by Python lines (like in the PET notebooks).

**Comment by KrisThielemans** [comment]
@danieldeidda we probably have no time to fix that this week I guess. Let me know.

**Comment by danieldeidda** [comment]
That data is on OSF https://osf.io/pcfb4/ which is the one used at NPL. There is a way to download data from there but at the time of the PSMR school it was not working

**Comment by KrisThielemans** [comment]
I've modified the notebook accordingly but keep the issue as it should be added to `download_data.sh`

**Comment by danieldeidda** [comment]
sure, I guess it would would need to go on the SPECT data download since there isn't one. However, when running the line above will also download PET data

**Comment by KrisThielemans** [comment]
@danieldeidda is there a chance this will ever be split in PET and SPECT data? Or even on Zenodo? If not, we should close this issue.

As the notebook works fine, I certainly don't want to modify anything now before 3.5.

**Comment by danieldeidda** [comment]
Hi, OSF was the NPL select way of sharing this. I'd rather not creating zenodo copies of the same data as this data has already been cited. If we want a separate PET and SPECT repository we possibly can create another one.

**Comment by KrisThielemans** [comment]
ok, if it already has a DOI, then I wouldn't duplicate it. That seems the wrong thing to do, even if it is for splitting.

So yes, if we ever got some other experimental data, then we can use that. Can still be NPL's preferred way of sharing of course.

So I'll close this issue.
