### ISSUE TITLE
Video Link For OOP not working 

### ISSUE THREAD

**Issue by rmapree** [SyneRBI/SIRF-Exercises#209]
notebooks/Introductory/object_oriented_programming.ipynb

The current link takes you to the webpage(for slides): http://www.ccpsynerbi.ac.uk/sites/www.ccppetmr.ac.uk/files/20170728_OOP_slides.pdf

Current link for recording: http://www.ccpsynerbi.ac.uk/sites/www.ccppetmr.ac.uk/files/Introduction_to_OOP_20170728.mp4

**Comment by KrisThielemans** [comment]
@paskino do you know where these went?

**Comment by evgueni-ovtchinnikov** [comment]
Sorry I was moving some stuff around for ease of downloading to my laptop and Dropbox - everything is back for now.
