### ISSUE TITLE
docker image out of date

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-Exercises#215]
https://github.com/SyneRBI/SIRF-Exercises/blob/33fae8f50c0403c58b5c22d152299e59704582ff/.devcontainer/devcontainer.json#L15

@casperdcl should this refer to `ghcr.io/synerbi/sirf:jupyter`?

**Comment by DANAJK** [comment]
Possibly related, using `acquisition_model_mr_pet_ct.ipynb` from Jupyter in Docker, at the PET section 

`templ_sino = pet.AcquisitionData(os.path.join(examples_data_path('PET'),"thorax_single_slice","template_sinogram.hs"))`

gives:

```
WARNING: Interfile warning: 'distance between crystals in axial direction (cm)' invalid.


WARNING: Interfile warning: 'distance between crystals in transaxial direction (cm)' invalid.


WARNING: Interfile warning: 'distance between blocks in axial direction (cm)' invalid.


WARNING: Interfile warning: 'distance between blocks in transaxial direction (cm)' invalid.
```

**Comment by KrisThielemans** [comment]
Sadly, those warnings are currently in STIR `master`. I forgot to clean them up. There's also going to be warnings about "nonTOF" scanners. Not great.

**Comment by KrisThielemans** [comment]
Probably related is https://github.com/SyneRBI/SIRF-SuperBuild/issues/865, which makes it sound like we cannot upgrade the devcontainer here yet.
