### ISSUE TITLE
fully_sampled_recon_three_chains fails

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-Exercises#31]
Same problem as https://github.com/CCPPETMR/SIRF/issues/293

**Comment by KrisThielemans** [comment]
Fixing the `ExtractGadget` is going to be hard. I suggest we comment it out and do instead
```python
import numpy as np
import sirf.Utiltities
...
real_image_array=np.abs(complex_image_data.as_array())
sirf.Utilities.show_3D_array(real_image_array)
```

**Comment by evgueni-ovtchinnikov** [comment]
Found bugs in ExtractGadget, created Gadgetron issue #743.

I feel the workaround applied was not a good idea - we no longer have three chains, so the name of the demo is confusing, and the single chain demo is still affected by one of the bugs (the first one in #743) anyway.

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov is this still relevant? We need to either fix this, or move the broken notebook(s) to a subfolder with a name `broken` or similar.

**Comment by evgueni-ovtchinnikov** [comment]
the notebook is actually ok except that it now should be called `fully_sampled_recon_two_chains`

**Comment by KrisThielemans** [comment]
great. Please "git mv" and adjust a README (if any), and close this issue then.

**Comment by KrisThielemans** [comment]
I've checked that it runs. I'm not sure about the naming, and it's fairly obsolete as a notebook anyway, so I'll just close this.
