### ISSUE TITLE
Can no longer install numba with python 2

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-Exercises#45]
The synergistic demos use brainweb, which starts by using `pip install numba`. That now fails:
```
 running bdist_wheel
  /usr/bin/python /tmp/pip-install-sW2ewi/llvmlite/ffi/build.py
    File "/tmp/pip-install-sW2ewi/llvmlite/ffi/build.py", line 122
      raise ValueError(msg.format(_ver_check_skip)) from e
                                                       ^
  SyntaxError: invalid syntax
```
Also seen here https://stackoverflow.com/questions/61925676/can%c2%b4t-install-numba-for-python with a comment "try a new version of Python".

Is there a work-around? Do we need numba or can we make it optional (without a lot of work).

This is currently a problem as our VM is still stuck on Python 2

**Comment by casperdcl** [comment]
I think `numba` is a leftover from some performance hacks @rijobro was trying - looks like it can be removed.

**Comment by rijobro** [comment]
yeah, it looks like it wasn't actually being used in the notebook. It is, however, used in a few others (but not `pip` installed): 

- https://github.com/SyneRBI/SIRF-Exercises/blob/master/notebooks/Synergistic/de_Pierro_MAPEM.ipynb
- https://github.com/SyneRBI/SIRF-Exercises/blob/master/notebooks/Synergistic/Solutions/Dual_PET_Answer-noMotion.ipynb
- https://github.com/SyneRBI/SIRF-Exercises/blob/master/notebooks/Synergistic/Solutions/Dual_PET_Answer-wMotion.ipynb

**Comment by KrisThielemans** [comment]
Serves us right from not upgrading to Python 3. @paskino, this will have to be a priority after 2.2 (unless it's a matter of dropping in ubuntu 20.04, but that seems unlikely!)

I suggest to move the `import numba` to a new cell, but commented out, saying that they can uncomment it and subsequent `@jit` lines if they have python3 (and numba).

**Comment by casperdcl** [comment]
How much of a speedup does it really give in those notebooks? May just be better to leave it out...

**Comment by rijobro** [comment]
Comment from a notebook says
> Using jit gets computation time from 90 secs to 2!

So I'm inclined to comment it out rather than delete.
