### ISSUE TITLE
MR-joint-TV demo needs fixing

### ISSUE THREAD

**Issue by DANAJK** [SyneRBI/SIRF-Exercises#54]
At least running via Docker, this demo seems to be missing a directory:

```
OSErrorTraceback (most recent call last)
<ipython-input-2-1f29d02172b2> in <module>()
     14 #%% GO TO MR FOLDER
     15 os.chdir(examples_data_path('MR'))
---> 16 os.chdir('johannes')

OSError: [Errno 2] No such file or directory: 'johannes'
```

**Comment by KrisThielemans** [comment]
good spot. In fact, this demo is currently still broken, as it says.  It's probably not a bad thing that it fails at the start, as the algorithm is wrong anyway...

I guess that we could fix it with new CIL (@paskino is that correct?).  But we don't have data for it at present either I believe, which is why we downloaded it during the exercise from Johannes somewhere. @johannesmayer, could you confirm that this (or similar) data is not yet on zenodo?

For now, I will just edit the text.

**Comment by KrisThielemans** [comment]
updated in c9380fe65ecd44eefec62b7a3b25a13a6ffa0b5d.

I will keep the issue open to remind us to fix this later.

**Comment by mscipio** [comment]
Even though this notebook is not yet functional, I was trying to take inspiration from the idea of a regularized MR reconstruction to build a separate test case.
However, when at the point of defining Gradients, it seems that the current version of `ccpi` does not ship with a method called :
```python
from ccpi.optimisation.operators import GradientSIRF
```

If I try to replace it with the only other option available:
```python
from ccpi.optimisation.operators import GradientSIRF
```
I get the following error:
![image](https://user-images.githubusercontent.com/17526160/92971444-77a2b600-f44e-11ea-91fd-4aea39b9cee5.png)


My guess is that the `GradientSIRF` function should act as a wrapper, providing CIL with the necessary info about the geometry. 

Is there any WIP version of `ccpi` where I can find an example of `GradientSIRF`?
Or, better, are there any other strategies I can use within SIRF to define the gradient to build my own regularized MR reconstruction, without having to write it by hand, from scratch?

**Comment by KrisThielemans** [comment]
@paskino @epapoutsellis @gemm can you remind us what the current status is of the gradient operators?

**Comment by epapoutsellis** [comment]
For CIL objects, please use `from cil.optimisation.operators import GradientOperator`.
For SIRF objects I had a `GradientSIRF` implementation which I cannot find atm. Maybe @paskino knows.
The other option is to use an [`FGP_TV`](https://github.com/vais-ral/CCPi-Framework/blob/master/Wrappers/Python/cil/plugins/ccpi_regularisation/functions/regularisers.py#L71) solver, where the gradient is computed in a C level, so not worry about sirf/cil objects

**Comment by KrisThielemans** [comment]
@Pakino wrote
> I think that since a while CIL GradientOperator can be used straight away with a SIRF DataContainer, no need for obscure workarounds.

**Comment by paskino** [comment]
I believe that this notebook is superseded by [cil_joint_tv_mr.ipynb](https://github.com/SyneRBI/SIRF-Exercises/blob/master/notebooks/Synergistic/cil_joint_tv_mr.ipynb) and this issue should be closed @KrisThielemans @DANAJK 

@mscipio I believe that the current version of CIL supports natively the `GradientOperator` on SIRF `DataContainer`s.

**Comment by KrisThielemans** [comment]
I agree. @ckolbPTB could confirm.

**Comment by KrisThielemans** [comment]
obviously, the obsolete notebook should be removed

**Comment by ckolbPTB** [comment]
yes, this notebook can be deleted.
