### ISSUE TITLE
overview of folder structure

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-Exercises#60]
We need an overview of where everything is, and where to start.

@DANAJK you suggested to have this in a notebook. I think I'd prefer to have it part of the README (potentially splitting that up in several notebooks). You can open those in the `jupyter` interface with reasonable formatting (although sadly links etc don't work). What do you think?

We could have both of course. Maybe update frequency is low enough that duplication doesn't matter.

If a notebook, I guess it would sit in the `Introductory` folder.

**Comment by DANAJK** [comment]
Did I? I agree it is better to have the folder structure information in a readme. 
I think I suggested a notebook to help with dimensions and geometry.

**Comment by KrisThielemans** [comment]
ok. There's https://github.com/SyneRBI/SIRF-Exercises/blob/master/notebooks/Introductory/introduction.ipynb, but it doesn't talk about geometry, dimensions nor MR.

**Comment by KrisThielemans** [comment]
created #61 for the latter. So this issue can be resolved by expanding `README`
