### ISSUE TITLE
SIRF VM: Error msg in reconstruct_measured_data.ipynb (PET)

### ISSUE THREAD

**Issue by Ede1994** [SyneRBI/SIRF-Exercises#63]
In the notebook 'reconstruct_measured_data.ipynb' (PET notebooks) I get the error:

error: ??? "'Error opening file template.hs\\n' exception caught at line 303 of /home/sirfuser/devel/buildVM/sources/SIRF/src/xSTIR/cSTIR/cstir.cpp; the reconstruction engine output may provide more information

after: lm2sino.set_up()

All the other notebooks went through without any problem.
Executed within VirtualBox 6.1.18 with the new .ova: SIRF_2.2.0_Python3.

**Comment by KrisThielemans** [comment]
This was fixed
