### ISSUE TITLE
MAPEM: adding different non-guided priors?

### ISSUE THREAD

**Issue by danieldeidda** [SyneRBI/SIRF-Exercises#69]
We discussed including different priors, I guess it would make sense to have them as part of this notebook. I guess the quadratic is always a good starting point and then we could have more interesting one like relative difference, logcosh? We could even give the function and the exercise would be to implement it

**Comment by KrisThielemans** [comment]
could you have a look at this? One thing to do would be to use the priors in SIRF as a first step, then see how to implement another one based on the SIRF-contrib code.

**Comment by danieldeidda** [comment]
> 
> 
> could you have a look at this? One thing to do would be to use the priors in SIRF as a first step, then see how to implement another one based on the SIRF-contrib code.

I guess the prior in SIRF is the one already in the notebook. Where is the SIRF-contrib code?

**Comment by KrisThielemans** [comment]
I think some of these use https://github.com/SyneRBI/SIRF-Contribs/tree/master/src/Python/sirf/contrib/kcl. haven't checked...

**Comment by KrisThielemans** [comment]
addressed by writing explanations and leaving it as an exercise to the student :-)
