### ISSUE TITLE
add requirements.txt

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-Exercises#77]
We need to preinstall some Python packages, see also https://github.com/SyneRBI/SIRF-Exercises/pull/76#issuecomment-827805531

- [x] add requirements.txt
- [x] modify documentation
- [ ] in our docker files, check if it exists and use it
- [ ] in VM files, check if it exists and use it

**Comment by KrisThielemans** [comment]
actually this is an almost duplicate of #40

**Comment by ashgillman** [comment]
NB: First two are ticked off here, but Docker and VM are TODO

**Comment by KrisThielemans** [comment]
Closing as new issues created
