### ISSUE TITLE
Working directory for each notebook to keep temporary files separate from input

### ISSUE THREAD

**Issue by ashgillman** [SyneRBI/SIRF-Exercises#84]
Per discussion in Devel meeting

**Comment by ashgillman** [comment]
Thoughts on where this working directory should go? @KrisThielemans @ckolbPTB @paskino others?

Other notebooks now are tending to put this under `exercises_data_path` which, by default, is a subdirectory from the project root, `data`.

I thought it might be easier for the user to locate these files if its a subdirectory of where the notebooks is located?
e.g., `notebooks/PET/ML_reconstruction.ipynb` makes a directory `notebooks/PET/ML_reconstruction_workdir` and 'cd's into there, symlinking in files from `exercises_data_path` or `examples_data_path`.

**Comment by ckolbPTB** [comment]
I would find it easier to have a central folder where all the temp files are, i.e. notebooks/Tmp/ML_reconstruction_workdir or something like this, such that it is easy to delete all of them rather than having to go to each subfolder in notebooks.

**Comment by KrisThielemans** [comment]
I agree a central folder is better. I would not put it in `notebooks/` though, as logically it doesn't make sense. `SIRF-exercises/data/workdir` or something like that? It does imply that we start the VM notebook server such that it sees higher up folders (at present it starts "in" `notebooks`), but we have to make this uniform with the docker images anyway (where the jupyter notebook server currently starts in  `/devel` such that it can see `/devel/SIRF-exercises`).

I think symlinks are possibly confusing for people (and maybe tricky to set up on Windows?). The PET notebooks tend to make a copy, which will be unfeasible for measured data as too large, but it should be possible to create output in the `workdir` with input from elsewhere. Better practice anyway

**Comment by ashgillman** [comment]
Okay, no worries. One more question before I can implement: is the workdir always in `SIRF-exercises/data/workdir`, or is it in `{exercises_data_path('workdir')}`?
I presume the latter - but this implies that we can't run any notebooks without running `download_data.sh` - even if they don't need any of the downloaded data. Is this acceptable?
Or does `{exercises_data_path()}` need to default to `SIRF-exercises/data`? Then we lose our error message - presumably we can work around this in the function though.
