### ISSUE TITLE
convertSiemensInterfileToSTIR.sh doesn't exist

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-Exercises#87]
It turns out this [only gets installed when `STIR_BUILD_EXECUTABLES=ON`](https://github.com/UCL/STIR/blob/42240decc608f18a2ad89f462309b5baa47c86cf/scripts/IO/CMakeLists.txt#L24-L26).

This is unfortunate... I guess we either copy it by hand somehow, or I release a new STIR version. Sigh.

**Comment by KrisThielemans** [comment]
@ashgillman any other ideas?

**Comment by KrisThielemans** [comment]
I've added a line in https://github.com/SyneRBI/SIRF-Exercises/commit/bb54d3c837da946c7031972ade0ffa089ba78eff. I guess this might resolve it

**Comment by ashgillman** [comment]
Sorry for the delay. Ah bugger - I think your proposed solution is a good temporary one until  UCL/STIR#894 makes it into mainline.

**Comment by KrisThielemans** [comment]
This is fixed on STIR master now. As soon as we update SIRF, we'll be ok. In any case, the work-around will help most people anyway.
