### ISSUE TITLE
Weird bug installing requirements.txt on VM

### ISSUE THREAD

**Issue by ashgillman** [SyneRBI/SIRF-Exercises#91]
I had a weird, repeatable bug on Michael's VM (from Edo) where running update_VM.sh would fail on `python3 -m pip -U -r requirements.txt` in SIRF-Exercises.

Pip was seg-faulting.

We had to remove all libraries in `~/.local/lib/python3.X` and re-run the script.

[This answer](https://stackoverflow.com/a/59025725) suggests this might have something to use of `--only-binary`, although I was unable to install without `--only-binary=llvmlite` and removing all other `--only-binary` flags didn't help...

I suggest we leave this issue open for a month or two and if no-one else runs into problems we close.

**Comment by KrisThielemans** [comment]
what's the value of the `--only-binary` anyway?

**Comment by ashgillman** [comment]
Well I confess I haven't dug into it deeply - perhaps I'll have a look tomorrow. My understanding is you install a pre-build binary so I added it to libraries with C-level, and that it would prevent you from having to build (i.e., quicker, potentially less space used, less chance of something going wrong in the build caused by compilers etc.)

**Comment by ashgillman** [comment]
I think this can be closed - we had no further issues on newer VM and `--only-binary` is being handled in #97
