### ISSUE TITLE
requirements.txt does it need to have --only-binary

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-Exercises#97]
`--only-binary` in `requirements.txt` [confuses ](https://github.com/SyneRBI/SIRF-SuperBuild/blob/9767f8adb189474e95f357ba1986e2755ba4a6dd/docker/user_service-ubuntu.sh#L10)the docker build

Do we need that?

**Comment by KrisThielemans** [comment]
> `--only-binary` in `requirements.txt` [confuses ](https://github.com/SyneRBI/SIRF-SuperBuild/blob/9767f8adb189474e95f357ba1986e2755ba4a6dd/docker/user_service-ubuntu.sh#L10)the docker build

yes, that first fails as `conda` doesn't have that option, but then `pip` picks it up, so I didn't bother fixing it when I saw this. Still, better to do it properly.

> Do we need that?

I think we can remove it. see https://github.com/SyneRBI/SIRF-Exercises/issues/91#issuecomment-849349791 and comments above and below..

probably also occurs in SIRF.

**Comment by ashgillman** [comment]
I was unable to install without --only-binary=llvmlite when experimenting recently - we just have to make sure that build dependencies are installed on the VM/Docker.

**Comment by KrisThielemans** [comment]
yes, but were you able to install with just `llvmlite` (or possibly you didn't try)

**Comment by ashgillman** [comment]
Okay, I tested locally and I don't need the `--only-binary`, but I did previously on the VM - how best to test with docker though?

**Comment by KrisThielemans** [comment]
once a service image is `up`, you can
```
docker exec -ti sirf /bin/bash
```
and you'll be in as `root`#, so you can do
```sh
sudo -u jovyan
cd /opt/SIRF-Exercises
sed -e 's/--only-binary=[^ ]*//' requirements.txt > ~/test2.txt
conda install --file ~/test2.txt
```
(still a bit awkward for permissions. No need for `/opt/SIRF-Exercises` to be owned by `sirfuser`, which I still need to change.)

Sadly, it then comes back with
```
PackagesNotFoundError: The following packages are not available from current channels:
  - brainweb[version='>=1.5.1']
```

It appears that this makes the whole `conda install` ab?ort, so the `Docker` script will fall back on `pip` anyway.

Seems we can just as well leave this alone for now

**Comment by KrisThielemans** [comment]
Removed in #187
